### ISSUE TITLE
Not optimized for mobile interfaces

### ISSUE THREAD

**Issue by manuelelucchi** [Giuseppetm/syndrome-main-computer#1]
"Wazowskyi, non ha completato le pratiche la scorsa notte"

**Comment by Giuseppetm** [comment]
1) Mobile interfaces ARE FOR BETAS
2) Syndrome non accedeva da telefono, BROCCOLO

☮️

**Comment by Giuseppetm** [comment]
The website is now optimized for smaller displays, but it won't have a support for responsive design since there isn't one in the movie.
