### ISSUE TITLE
Searching for Mr. Incredible takes you to show that he was terminated by Omnidroid v.X9

### ISSUE THREAD

**Issue by Robotboy13** [Giuseppetm/syndrome-main-computer#10]
![image](https://github.com/Giuseppetm/syndrome-main-computer/assets/137990056/f217236f-0f65-4eb4-8242-d166452fed11)

**Comment by Giuseppetm** [comment]
Thank you for the issue,
I will implement a dynamic search feature for all the supers shown in the movie as soon as possible. 👍🏻
