### ISSUE TITLE
react-scripts not found

### ISSUE THREAD

**Issue by Mirage3098** [Giuseppetm/syndrome-main-computer#12]

**Comment by Giuseppetm** [comment]
Hello @Mirage3098 

Did you install the dependencies with `npm install` command?

**Comment by Mirage3098** [comment]
I tried, but it came up with npm WARN and said something about the package.json being made with old version of npm or something.

**Comment by Giuseppetm** [comment]
> I tried, but it came up with npm WARN and said something about the package.json being made with old version of npm or something.

Try using node v14 (use nvm for version manager)
